apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wisecow-app
    spec:
      containers:
        - image: adarsh435/wiscow:v1
          name: wisecow-app
          resources:
            limit:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 4499
