apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  labels:
    app: wisecow-app
spec:
  selector:
    app: wisecow-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 31000
  type: NodePort
